import Home, { HomeProps } from "@/components/Home";
import Layout from "@/components/Layout";
import { useTrendContext } from "@/context/trendContext";

export async function getStaticProps() {
  //   // Fetch data from external API
  //   // const res = await fetch('http://hermesproject.pythonanywhere.com/trends', { headers: new Headers({ 'X-API-Key': 'Q%o4V#h6Rt@1m5Z&9aG' }) })
  //   // const data = await res.json()
  //   // Pass data to the page via props
  const data = [
    {
      negative_count: 1,
      positive_count: 0,
      trend: "Lazarus of Bethany",
      tweet_types: {
        regular: ["I dont care about Lazarus of Bethany"],
      },
    },
    {
      negative_count: 0,
      positive_count: 0,
      trend: "#SundayLegal",
      tweet_types: {},
    },
    {
      negative_count: 36,
      positive_count: 140,
      trend: "Thailand",
      tweet_types: {
        figurative: [
          "POLITICAL unrest in thailand = brother not going = no car for two weeks for me. Fuck you thailand trannies ",
          "@RobinThailand Unfortunately not ",
          "@Aceofcups Yay, sounds good! By the way, The Narrative IS coming to NYC, at a 21+ venue, after I leave for Thailand. ",
          "@cyberbaguioboy Thailand? Naga? Yiiiiiiiiiikes. ",
          "@RobinThailand Waaah! Will not make Barcamp Bangkok next weekend as my school is taking my passport for HK Visa renewal  WIll you stream?",
          "I wanna go to DBSK oppa's Mirotic Concert in Thailand!!! I REALLY WANNA GO SO MUCHHHHH...    burst into tears",
          "Disturbed. They sold the baby tiger I met in Thailand as an exotic pet. Greedy bastards ",
          "Can't give blood for a year since I went to Thailand!!  oh well the trip was worth it!!",
          "@tommcfly 's tweet made me miss thailand even more. ",
          "can't find my wetsuit or kiteboard  when and where did I use last time? Koh Chang thailand... 4months ago",
          "@chereer Hey husband lost job today due to economic crisis don't think we are going to get to go on any holiday soon let along Thailand ",
          "A colleague from Thailand I've worked with many times and has been suffering from cancer passed away last night. Crying on train. ",
          "#thailand rain is horizontal here (suan siam). mango tree appears drunk. plants scattered every which way. more destructive testing ",
          "@140horror i wanna watch Funny Games!!! it got banned in thailand...suck ",
          "trying not to panic about the fact I can't find my email confirmation for Thailand flights in August.  Trying, and failing ",
          "daytime tv is heartbreaking! Some poor guy buying a wife in Thailand and she's taking all his money ",
          "Yup. He was found in his hotel room in thailand hanging from a rope in his closet  [\u00c2\u00a4]",
          "Thailand keeps stealing my best friends ",
          "You die, tragically, in Thailand.  And you get something like this from a 'friend' on Facebook:   What sad, pathetic creatures we are.",
          "@H2_TheMovie Halloween got banned in thailand  sucks..i wanna watch it so much!!",
          "I really wish I could get $1000 for Thailand ",
          "Looking for English-teaching jobs in Thailand is making me feel incompetent ",
          "Where is the Sun ... the world is 2 grey    I miss Thailand",
          "going to return all her thailand stuff back to millets ",
          "Mom just left for Thailand again  hanging out with my bro in SF",
          "http://yfrog.com/0pk12wj I miss my puppy in Thailand ",
          "@doublebeat I'ts been raining a lot in Thailand lately ",
          "I hate fake people... @metallicsharpie have a safe flight to thailand! I'll miss you ",
          "windy day in pattaya thailand... today i am feeling bad, eat something worng yesterday.. couldnt go to a show in the morning..  ",
          "lar is going to Thailand without me! ",
          "two more days with mommy before she goes back to Thailand ",
          "Omg this reminds me of an early morning in thailand  i miss thailand so much",
          "@gemdealer is ranked 94,883 on Twitterholic.com, and 16 in Thailand! http://twitterholic.com/gemdealer/ Twittergrader has me lower ",
          "@sarahmaemae that's the dog that i want. i had to decide between a dog or my trip to thailand...mike said i had to give the dog back ",
          "i'm back and it was a terrible holiday. thailand i'm not coming back again. ",
          "4 more sleeps till thailand, to much work to do up until than ",
          "@miss_melbourne Same!!! Especially this time of the year when there's sooooo much fruit. I could live on fruit in Thailand. I miss it ",
          "sigh. 705 cases in thailand. bangkok next weekend is a bad idea. what do you think?  i've been anticipating this for ages though.",
          "I don't wanna go to Thailand ",
          "Back to my second world ...Amazing Thailand...I shall savour it as I don't know if i'll make it next year ",
          "Transformers at the iMax was awesome! Tiring weekend helping with UKeSA LAN finals and the g/f leaves moving back to Thailand tomorrow ",
          "going to Thailand and Vietnam in 5 days yay! ",
          "@eccabilis We'll be in Rome after Thailand. Thanks for the Philippines invite. ",
          "@macmuso maybe Thailand as a base for a while, then I'd like to go to central and south america. Everywhere in time ",
          "@soccormom&gt;Only just if u also send to me one in Thailand  Than become international ",
          "@sylvied school trip to Phuket Thailand, I was 12 while living in Singapore ",
          "@dougiemcfly Hi Dougie I'm your fan from Thailand. I'm Film 'Luv ur song so much ",
          "quitting my beloved job... having a long luvly  vacation at Koh Tao (turtle island), south of Thailand... SEA, SAND, SUN...WANNA JOIN ME? ",
          "Working up to my vacation to Thailand. Getting more excited every day ",
          "@hitechhall I love the site what a hoot, really enjoy the hair cuts in Thailand, always try to time ir just right, thanks for the tip ",
          "@giladby In rural #thailand, 2630 is considered posh ",
          "@codymckibb thanks Cody! U were a big inspiration  I'll hit you up when I make it to thailand in a few months.",
          "hahaha....school is over but I'm still up...gotta be prepared for the time difference in Thailand ",
          "@gcimagess thailand? ",
          "@RealHughJackman going to Thailand and playing an extra in a film ",
          "@RealHughJackman Thailand - Phuket  You?",
          "Thailand has been wonderful, so many contrasting elements and experiences ",
          "@Bkk_Saluja i'm DYING to visit thailand, so hopefully 2010! why don't you meet me in India this fall? or better yet - the states?? ",
          "@StopChronicPain He's already left! (connecting from Dubai).  Ya he's just going on a honeymoon / vacation type deal...  #Thailand",
          "I love Thailand !!! I see why place is call land of thousand smiles   http://bit.ly/rh2vA",
          "@idpthailand I'm interesting in the English Training at UK. My contact email address is orapan.sphere@gmail.com Thks fr yr kind support. ",
          "@WillieCrawford Thailand, then we can meet up for a coffee ",
          "@burbholio I'm no. 1 on Google UK &amp; Thailand!? Kewl. I'm a star! ",
          "@Kathlene_SMM love thailand for real. Wanna make it my home ",
          "officially survived a week in Thailand with no parents ",
          "@frogblogger yes, i stay in pattaya thailand....    will go out for dinner.. will report in my blog later.",
          "is hangin out in mahasarakham thailand! ",
          "@poorprogrammer now Thailand SPIN start PPQA working group then you can join it if interesting ",
          "going to Thailand in July! ",
          "in Thailand  being a backpacker again makes me happy",
          "is officially going to Thailand! Just booked my ticket!!!!!!! Wooo wooo!!!!! ",
          "Tweeting from Laos! In Vientiane by the river, ironically looking at Thailand ",
          "Just received the e-ticket from govolo! Thailand here I come! ",
          "Thailand-101: jykthemuse has added a photo to the pool:   mmm. me love currrrrrry   Nikon FE2 / Nikkor 35.. http://bit.ly/x3aA7",
          "@RobinThailand sounds great - keep me in the loop - sounds very interesting ",
          "@eskudder take me to thailand! we need to sit down and plan ",
          "Just wrote a really long letter on paper for one of my best friends - Meliisa - who's living in Thailand. I really had much to say! ",
          "@CarlWeaver so you might have change the environment. let's come to thailand. ",
          "Just bought plane tickets from Bangkok, Thailand to Ho Chi Minh City, Vietnam  One plane ticket down, two to go!",
          "Who want to go to Thailand? Who love beach? ... I m here ",
          "@BevClement @StorySeeker you forgot HK and Thailand  &lt;~ what was this about Bev? (Sorry - having a mini senility attack)",
          "IN THAILAND ! it's very hot ! we're gonna play tennis &amp; probably go swimming ! i'm a dog, nicole's a mouse/horse/monkey &amp; harold's a cat ",
          "@usagi429 Where are you? Have you safely arrived in Thailand? ",
          "goin thailand sooooooon ",
          "@loris_sl might end up going either to Egypt or Singapore/Thailand  - what is your book about?",
          "@IzaEn tanning in thailand? ",
          "Original tasty thai food in Pattaya thailand.... You cant eat better, healthier and cheaper. See pictures in my blog daily updated  ",
          "@turbow worse in which way ka P'bow ..  u r still in Thailand .. wow cool ))))))",
          "@JayLx Lol Ur Lucky In Thailand!!! How Yu Doin B? I Was Wonderin wat hapend 2 u x ",
          "Hope you will love my country... &quot;...Thailand... The Land of Smiles...&quot;  ",
          "btw my granny arrived yesterday frm london ,, WHopeee she'z comin wth us to Thailand ",
          "Alright everybody, tomorrow I'm off on a cross-Thailand bike trip.  Back in mid-July. No laptop/phone, please don't email me  ",
          "@MyThailandBlog wow, that sounds amazing.  Where is Pattaya located? ",
          "we are moving to Thailand, period! ",
          "Exam = done   Thailand = next ",
          "72 Hours Amazing Thailand Hua Hin and Beyond Press Conference tomorrow at 10am at Erawan. Media friends, please show up ",
          "@lifeinthenavy hey if you wanna a break from it you can come to beaufort and i will go to thailand ",
        ],
        irony: [
          "says supposed to be tonight ang aming flight to thailand  http://plurk.com/p/p5eud",
          "@antony_yiu I was in Singapore and Thailand for a week or so. Back in Cali now ",
          "Last day of short Thailand vacation    Had a great time, as usual ;) More updates later...",
          "Didn't manage to get a pair of converses on Thailand  will try in Taiwan..",
          "I'd love to be on an island in Thailand about now. But it ain't on the cards ",
          "@magikfaces Aweee I'm soooo jealous dying lol I think I'm going thailand but ",
          "http://twitpic.com/6f5m6 - my brother in Thailand. Going to miss him, going for a whole year without his smiling face. ",
          "my girl off to Thailand for a month. She should land by now! Miss her already ",
          "@1stvamp In Thailand. Not too sure how it happened. I wasn't mugged, but everything disappeared from my bag at a bar. ",
          "@BradleyF81 Wow, Phuket is beautiful, they say. It's bad I need visa for Thailand  Bummer!",
          "@johnnycynn haha adina wants to go to thailand  i was like LETS GO TO CALIFORNIA! but she said no.. maybe next yr ill go to cali  ",
          "Mummy's flying to thailand tomorrow, feel like sending her off at the airport.. but.. 8am, alone? I miss taking flights  Boohoo.",
          "Baby is out. Apple is eating and I'm so bored. I want to go thailand soon. I miss shopping.  - http://tweet.sg",
          "boo my eyes are not working either.I love Thailand though.just wishing that my stomach wasnt this swollen.&amp;empty!!my feet are swollen too ",
          "Nokia has a very good music store to support record label to sell their songs ... Including Thai song but not available in thailand  ",
          "#thailand oh how i hate to be saying this but the beer at twang dang ramindra has gone downhill ",
          "@AjanMike i believe i asked if i was the only one NOT watching it...way to pay attention to me  hope thailand is awesome!",
          "@Yvonne_Lim You make me feel like eating Thai food now. I like beef kway teow but they cook it better in Thailand rather than Singapore. ",
          "I wannnnnnnaaaaaaa go to Thailand  I needs a holiday NOW!!!!!!",
          "Brazil: Rogue Criminal Nation? http://tinyurl.com/nmn6n9 Brazil has a child prostitution problem, second only to that of Thailand ... \u00e0\u00b8\u00ad\u00e0\u00b8\u00b2\u00e0\u00b8\u00a2 ",
          "im so draineeeed! i just want to go and fly over to thailand to do some major shopping now. ",
          "i can't believe this is the last day with @Nnnicolee in thailand  tomorrow last day for me in thailand! nicole's here for 2 weeks more! =(",
          "@TVXQUKnow: why did you make your concert in ThaiLand but not VietNam ?? ",
          "leaving to go shopping ! my last day in thailand !  leaving TODAY ! actually tomorrow about 1 am, but i have to be at the airport today !",
          "@miss_melbourne I was watching this and thought of Thailand. I miss Thailand now  Nothing like walking through those markets in asia.",
          "Daddy flew off to Thailand ",
          "Need to take a long vacation (Thailand) but can't afford that now as I would need a &quot;stimulus package&quot; first.  ",
          "@McLaughlin had quite a lot in the last 6 months: New Zealand, Thailand and Japan. Great trips ",
          "@RobinThailand Thanks. I have that one on the list in a few ways. ",
          "@deafmom tell your friend to invite me and don to Thailand! ",
          "BBC states that there is endemic corruption in Thailand,  (it seems that some British ministers of Parliament aren't immune either ",
          "Just had my first #Skype phone conversation with my brother in Thailand. The delay was pretty horrible, but it was cool to talk to him ",
          "we're sincerely welcome flatworld thailand new merchants (who just joined us), we're so happy to have your guys being with us, thank you ",
          "A wave of mixed emotions has hit, but Thailand will always be here, and I get to see my @zachfirquin tmrw ",
          "successfully obtained  visa entries to enter  and stay in the Royal Kingdom of Thailand! ",
          "@TamaraSchilling I have miss you too! I am currently in Thailand #BZW the Internet has it's own mind..  How are you!?!x ",
          "It's days like this that make me forget how much I miss Thailand  http://yfrog.com/6qluej",
          "@pcdnicole see ya 2morrow nicole. i'll fly from thailand just to see you. i made a poster 4 u. u'll see it at the concert. First row ",
          "@Axika http://twitpic.com/6qh41 - here in Thailand...we just got 'baby panda' ...!!!  ",
          "@mmangen I was in Thailand for 2 weeks. I have family there. I've been there several times before ",
        ],
        regular: [
          "Working  but looking 4ward 2 thailand and this weeks bank holiday weekend!",
          "missing Thailand ",
          "Really really sad news today.  David Carradine was found dead in his hotel room in Thailand  http://tinyurl.com/pnrza5",
          "@jumpingcastle roll call went soooo slowly without you all week  hows thailand!?!?!? miss you xx",
          "Analyst consumer financial market in Thailand. ",
          "@the12kingstar I'm ok. Just got back frm Bangkok, Thailand. Thats e good news. The bad news is that e Airline lost my check-in luggage. ",
          "My last night in Thailand and I have to wake up at 4:45 tomorrow morning ",
          "@Webleedhiphopit's already perfect !  we dont have this kinda site much in thailand,i love it! n i'll tell ma friends to visit ur site ayt",
          "@asin then go to thailand, amazing country  better go to islands, it's a paradise",
          "Pegel..cape ya keliling kuil..but,totally awesome!was amazed by the temple,culture,ambience..truly amazing thailand ",
          "Heading off to #Thailand tonight. Look out for updates ",
          "@minnac Thailand! Kun poh means father I believe ",
          "Packing for Singapore is so tiring, haha! Can't wait to reach Thailand, too!! ",
          "will return to the Samui Archipelago (Siam Bay, Thailand) July 3 until August 19. ",
          "Poto2x di Thailand http://bit.ly/vftex  ",
          "@JJNextGenTV 6 weeks, Jun28, Kenya/ Ethiopia/ Thailand. But 1st the 48hr tweetfest to raise the money for the schools 17-19Jun. #GHNI ",
          "will put pix in my pattaya photo blog asap.. i promise #thailand ",
          "Thailand 16 days ",
          "@RobinThailand I love messages from the future  Just having a look at xtranormal.com - v cool.",
          "Off to Thailand to live and work in less than two weeks ",
          "to @Thaitech - Monza :  Thailand should use twitter for the next revolution - seems to be doing well in Iran  Hope you are well",
        ],
        sarcasm: [
          "@bangkokpundit the line's so blurred in Thailand depending on agendas, interests, I doubt anyone really knows, even those with an agenda ",
          "@holeymacaroney Super green sya parang.. uh Okra? Basta, kawawa.  Try mo isearch sa youtube. Hmmm.. &quot;green baby thailand&quot; Haha im not sur",
          "p.s. the whole word limit thing sucks !  i have to write it in parts ! boo hoo i'm sad. no i'm not. i'm in thailand, oh yes i am! xxx NEA",
          "@moonlady The more I hear of the story the more depressed I get  Dying in Thailand seems bad enough. I just imagine the surroundings...",
          "@Jules75 thanks, love the necklace, Ive been trawling ibiza for a new 1 but with no luck  its gorgeous here, bet u cnt wait til thailand!",
          "@MLDina Too bad I'm in Bangkok, Thailand. My flights would take longer than a the time I would get to explore ",
          "Too bad i am not from Thailand. I would open a restaurant in Fulda Germany right now. Going to eat american then. Hello Mc Donald's ",
          "packing for thailand, why is my rucksack so small??  !!",
          "@MyThailandBlog wow XXO looks fun, but not for me!  but maybe for you ;-)",
          "@tiphereth Ta. Must be new profile pic day.  Thailand top of holiday list so far. Not for a few months though - probably a winter escape.",
          "@technotetris He's going to thailand for a holiday  lucky him!!",
          "@perrinl Wow... Great, I'm going to follow you! I'm going to backpack next month in Cambodia, Vietnam, Laos and Thailand ",
          "@stevenandchris Love to see you guys on Twitter now! Miss you, wish I were there - say hello to Thailand for me. ",
          "@luckyinthailand wow- THANKS! I didn't know this was up!  LOVE IT",
          "@ninnoart Well I've never been to the East. And I dont really care for it. Well maybe Thailand and Malaysia.  Danes travel a lot! A LOT",
          "Ever something unbelievable, strange or weird happened in pattaya? Just smile, because TiT - This is thailand       http://tr.im/nazV",
          "@sasatothemax Not Texas, Arizona  - Have you ever been to America? Yes, Thailand is beautiful...how about Indonesia?",
          "just had lemon grass drink - always so refreshing, and it gives a good memory of thailand ",
        ],
      },
    },
    {
      negative_count: 0,
      positive_count: 0,
      trend: "The Corinthians",
      tweet_types: {},
    },
  ];

  return { props: { trends: data } };
}

export default function Index({ trends }: HomeProps) {
  return (
    <>
      <Layout>
        <Home trends={trends} />
      </Layout>
    </>
  );
}
